function wage_growth_numbers_shock = calc_shock_wage_growth(C, shock_trans,...
    one_trans, ...
    theta_grid, high_wage, low_wage, ...
    start_wage)

    wage_growth = zeros(size(theta_grid'));
    abs_wage_growth = zeros(size(theta_grid'));
    for i=1:size(theta_grid', 1)
        [wage_growth(i,:), abs_wage_growth(i,:)] =...
            calc_single_bin_end_wage_shock(i, C, shock_trans, one_trans,...
                                     theta_grid, high_wage, low_wage, ...
                                     start_wage(i,:));
    end
    
    wage_growth_numbers_shock = [wage_growth, abs_wage_growth];
end
