function [wage_growth_numbers, distmat, wagemat] = calc_wage_growth(s0_trans, ...
    s1_trans, s0_intercept, s1_intercept, omega, theta_grid, ...
    n_periods, high_wage, low_wage, ...
    start_wage)

    wage_growth = zeros(size(theta_grid'));
    abs_wage_growth = zeros(size(theta_grid'));
    distmat = zeros(length(theta_grid), length(theta_grid));
    wagemat = zeros(length(theta_grid), length(theta_grid));
    for i=1:size(theta_grid', 1)
        [wage_growth(i,:), abs_wage_growth(i,:), distmat(:,i), wagemat(:,i)] =...
            calc_single_bin_end_wage(i, s0_trans, ...
                                    s1_trans, s0_intercept,... 
                                    s1_intercept, omega, ...
                                    theta_grid, n_periods, ...
                                    high_wage, low_wage, ...
                                    start_wage(i,:));
    end
    
    wage_growth_numbers = [wage_growth, abs_wage_growth];
end