function wage_pctile_numbers = calc_wage_growth_lt_pctile(C, ss_trans, theta_grid, ...
                                                          high_wage, low_wage, ...
                                                          start_wage, pctile_wage)

    wage_pctile_ids = zeros(size(theta_grid'));
    for i=1:size(theta_grid', 1)
        wage_pctile_ids(i,:) =...
            calc_single_bin_pctile(i, C, ss_trans, theta_grid,...
                                   high_wage, low_wage, ...
                                   start_wage(i,:), pctile_wage);
    end
    
    wage_pctile_numbers = wage_pctile_ids;
end