function wage_pctile_numbers = calc_wage_growth_lt_pctile_shock(s0_trans, ...
    s1_trans, s0_intercept, s1_intercept, s0_pz_trans, s1_pz_trans, ...                                    
    s0_pz_intercept, s1_pz_intercept, omega, theta_grid, ...
    n_periods, high_wage, low_wage, ...
    start_wage, pctile_wage, shock)

    wage_pctile_ids = zeros(size(theta_grid'));
    for i=1:size(theta_grid', 1)
        wage_pctile_ids(i,:) =...
            calc_single_bin_pctile_shock(i, s0_trans, ...
                                    s1_trans, s0_intercept,... 
                                    s1_intercept, s0_pz_trans, s1_pz_trans, ...
                                     s0_pz_intercept, s1_pz_intercept, omega, ...
                                    theta_grid, n_periods, ...
                                    high_wage, low_wage, ...
                                    start_wage(i,:), pctile_wage, shock);
    end
    
    wage_pctile_numbers = wage_pctile_ids;
end