function wage_growth_numbers_shock = calc_shock_wage_growth(s0_trans, ...
    s1_trans, s0_intercept, s1_intercept, ...
    s0_pz_trans, s1_pz_trans, ...
    s0_pz_intercept, s1_pz_intercept, ...
    omega, theta_grid, n_periods, high_wage, low_wage, ...
    start_wage, shock)

    wage_growth = zeros(size(theta_grid'));
    abs_wage_growth = zeros(size(theta_grid'));
    for i=1:size(theta_grid', 1)
        [wage_growth(i,:), abs_wage_growth(i,:)] =...
            calc_single_bin_end_wage_shock(i,s0_trans, ...
                                     s1_trans, s0_intercept, s1_intercept, ...
                                     s0_pz_trans, s1_pz_trans, ...
                                     s0_pz_intercept, s1_pz_intercept, ...
                                     omega, theta_grid, ...
                                     n_periods - 1, high_wage, low_wage, ...
                                     start_wage(i,:), shock);
    end
    
    wage_growth_numbers_shock = [wage_growth, abs_wage_growth];
end