function end_grid = single_period_change(grid, s0_trans, s1_trans,...
    s0_intercept, s1_intercept, omega)
    end_grid = (1 - omega) * (s0_trans * grid + s0_intercept) ...
        + omega * (s1_trans * grid + s1_intercept);
end