function low_wage = w_l(H, L, xi, rho, sigma, mu, lambda, v, H_inside) 
  if H_inside == 0
      low_wage = ((1 - mu) * ...
          (lambda * xi ^ rho - L ^ rho * (-1 + lambda)) ...
          ^ (sigma / rho) + ...
          mu * H ^ sigma) ^ (v / sigma) * ...
          v * (-1 + lambda) * (lambda * xi ^ rho - L ^ rho * ...
          (-1 + lambda)) ^ (sigma / rho) * (-1 + mu) * L ^ rho / ...
          (lambda * xi ^ rho + (1 - lambda) * L ^ rho) / L / ((1 - mu) * ...
          (lambda * xi ^ rho - L ^ rho * (-1 + lambda)) ^ (sigma / rho) + ...
          mu * H ^ sigma);
  else
      low_wage = ((1 - mu) * (lambda * xi ^ rho - ...
          H ^ rho * (-1 + lambda)) ^ (sigma / rho) + ...
          mu * L ^ sigma) ^ (v / sigma) * v * ...
          mu * L ^ sigma / L / ((1 - mu) * ...
          (lambda * xi ^ rho - H ^ rho * ...
          (-1 + lambda)) ^ (sigma / rho) + ...
          mu * L ^ sigma);
  end
end